### PR TITLE
Basic trolley skip button

### PR DESCRIPTION
**Pull request by HiddenKitten**
this definitely can be done more elegantly, having the client tell the server to abort the minigame probably isn't the best, although I doubt most people will be on archipelago specifically to play minigames with friends, so it's *probably* fine.

screenshot_skip_button

currently trying to figure out how to avoid when skipping toon slingshot, the umbrella stays attached to my toon.

### CODE REVIEW

**Comment by DarthMDev** [comment]
Love this I would probably move the skip button to the top right of the white box, where the title of the game text is  and above the description

**Comment by HiddenKitten** [comment]
Note for merging this: if a trolley check is ever added, check for earning something like 100 jellybeans - skipping counts as completing a minigame, and due to our multiplier, toons earn jellybeans before the minigame timer even finishes counting down.

**Comment by DarthMDev** [comment]
Can you show what it looks like in-game now?
Otherwise LGTM :)

**Comment by HiddenKitten** [comment]
Of course, I did end up using your suggestion for where to put it, for a moment when it was suggested, I thought about the names, but I don't think any minigame's name is that long, and didn't come across any while ~~crashing~~ testing.

https://github.com/user-attachments/assets/701404b2-f8c5-4cdd-8c87-99a4251e8b73

**Pull request merged**
